---
- name: copy script check domain exist
  template:
    src: check_domains.sh.j2
    dest: /tmp/check_domains.sh
    mode: 755
  tags:
    - vhost

- name: copy script check user exist
  template:
    src: check_users.sh.j2
    dest: /tmp/check_users.sh
    mode: 755
  tags:
    - vhost

- name: running the script check domain exist
  shell: bash /tmp/check_domains.sh
  register: command_result
  tags:
    - vhost

- debug: var=command_result
  tags:
    - vhost

- name: running the script check user exist
  shell: bash /tmp/check_users.sh
  register: check_users_result
  tags:
    - vhost

- debug: var=check_users_result
  tags:
    - vhost

- name: random string
  shell: head /dev/urandom | tr -dc A-Za-z0-9 | head -c 1 ; echo ''
  delegate_to: localhost
  register: rand
  tags:
    - vhost

- name: change user_domain if user exist
  shell: "sudo sed -i 's/\user_domain: .*/user_domain: {{user_domain}}{{rand.stdout}}/g' group_vars/all"
  delegate_to: localhost
  when: check_users_result.stdout=="1"
  tags:
    - vhost

- name: change group_domain if user exist
  shell: "sudo sed -i 's/group_domain: .*/group_domain: {{group_domain}}{{rand.stdout}}/g' group_vars/all"
  delegate_to: localhost
  when: check_users_result.stdout=="1"
  tags:
    - vhost

- name: change mysql_database if user exist
  shell: "sudo sed -i 's/mysql_database: .*/mysql_database: {{mysql_database}}{{rand.stdout}}/g' group_vars/all"
  delegate_to: localhost
  when: check_users_result.stdout=="1"
  tags:
    - vhost

- name: change mysql_user if user exist
  shell: "sudo sed -i 's/mysql_user: .*/mysql_user: {{mysql_user}}{{rand.stdout}}/g' group_vars/all"
  delegate_to: localhost
  when: check_users_result.stdout=="1"
  tags:
    - vhost

- name: create user owner website
  user:
    name: '{{ user_domain }}'
    create_home: no
  ignore_errors: yes
  tags:
    - vhost

- name: create group owner website
  group:
    name: '{{ group_domain }}'
    state: present
  ignore_errors: yes
  tags:
    - vhost

- name: update password user ftp
  shell: echo '{{ ftp_pass }}' | passwd --stdin '{{ user_domain }}'
  tags:
    - vhost

- name: create folder contains website
  file:
    path: /home/{{ user_domain }}/domains/{{ server_name }}/public_html
    state: directory
    mode: 755
    owner: '{{ user_domain }}'
    group: '{{ group_domain }}'
  tags:
    - vhost


- name: create folder contains vhsot
  file:
    path: /etc/nginx/conf.d
    state: directory
    
- name: copy nginx.conf file
  copy:
    src: nginx.conf
    dest: /etc/nginx/

- name: copy template vhost file
  template:
    src: vhost.conf.j2
    dest: /etc/nginx/conf.d/{{ server_name }}.conf
  ignore_errors: yes
  tags:
    - template-1


- name: copy template vhost file
  template:
    src: vhost-2.conf.j2
    dest: /etc/nginx/conf.d/{{ server_name }}.conf
  ignore_errors: yes
  tags:
    - template-2

- name: create file log
  file:
    path: /var/log/nginx/domains
    state: directory

- name: restart Nginx service
  service: name=nginx state=restarted
  ignore_errors: yes
  tags:
    - vhost
    
- name: chmod folder /home
  shell: find /home/{{ user_domain }} -type d -exec chmod 755 {} \;
  tags:
     - vhost
