---

- name: add repo mariadb
  copy:
    src: MariaDB.repo
    dest: /etc/yum.repos.d/

- name: install mariadb
  yum: name={{ item }} state=present
  with_items:
    - MariaDB-server
    - MariaDB-client

- name: install the Python MySQLB module
  yum: name={{ item }} state=present
  with_items:
    - python
    - python-pip
    - python-setuptools
    - MySQL-python

- name: create user password mysql
  copy:
    content:
        "[client] user=root password={{ mysql_pass_root }}"
    dest: /root/.my.cnf

- name: start mariadb service
  service: name=mariadb state=started enabled=yes


- name: create database name
  mysql_db:
    name: '{{ mysql_database }}'
    state: present
  tags: mariadb

- name: create user database
  mysql_user:
    name: '{{ mysql_user }}'
    password: '{{ mysql_pass }}'
    priv: '*.*:ALL'
    state: present
  tags: mariadb
